services:
    - type: web
    name: faturaxpress-api
    runtime: docker
    dockerfilePath: ./Dockerfile  # <- agora na raiz
    rootDir: .
    envVars:
            - key: DATABASE_URL
        sync: false
            - key: SECRET_KEY
        generateValue: true
