services:
    - type: web
    name: faturaxpress-api
    runtime: docker
    dockerfilePath: ./apps/api/Dockerfile
    rootDir: .  # <- importante: raiz do projeto
    envVars:
            - key: DATABASE_URL
        sync: false
            - key: SECRET_KEY
        generateValue: true
