"""agt final nc

Revision ID: 13bc80f10688
Revises: 60e2ac469d09
Create Date: 2026-09-16 01:01:53.150027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13bc80f10688'
down_revision: Union[str, Sequence[str], None] = '52f9d0dbce22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema - AGT final NC."""
    # ### commands auto generated by Alembic ###
    op.add_column('fatura_itens', sa.Column('motivo_isencao', sa.String(length=100), nullable=True))
    op.add_column('faturas', sa.Column('numero_nota_credito', sa.String(length=50), nullable=True))
    op.add_column('faturas', sa.Column('fatura_origem_id', sa.UUID(as_uuid=True), nullable=True))
    op.add_column('faturas', sa.Column('motivo_credito', sa.String(length=200), nullable=True))
    op.add_column('faturas', sa.Column('motivo_isencao', sa.String(length=100), nullable=True))

    op.alter_column('faturas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    op.create_index('ix_faturas_hash', 'faturas', ['company_id', 'hash_agt'], unique=False)
    op.create_index(op.f('ix_faturas_numero_nota_credito'), 'faturas', ['numero_nota_credito'], unique=False)
    op.create_unique_constraint('uq_company_numero_nc', 'faturas', ['company_id', 'numero_nota_credito'], deferrable=True, initially='DEFERRED')
    op.create_foreign_key('fk_faturas_fatura_origem', 'faturas', 'faturas', ['fatura_origem_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic ###
    op.drop_constraint('fk_faturas_fatura_origem', 'faturas', type_='foreignkey')
    op.drop_constraint('uq_company_numero_nc', 'faturas', type_='unique')
    op.drop_index(op.f('ix_faturas_numero_nota_credito'), table_name='faturas')
    op.drop_index('ix_faturas_hash', table_name='faturas')
    op.alter_column('faturas', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('faturas', 'motivo_isencao')
    op.drop_column('faturas', 'motivo_credito')
    op.drop_column('faturas', 'fatura_origem_id')
    op.drop_column('faturas', 'numero_nota_credito')
    op.drop_column('fatura_itens', 'motivo_isencao')
    # ### end Alembic commands ###
