"""atraso rh admin flow

Revision ID: 265a4f156395
Revises: 554633d9841b
Create Date: 2026-09-21 18:28:50.666466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '265a4f156395'
down_revision: Union[str, Sequence[str], None] = '554633d9841b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('funcionarios', sa.Column('ultimo_reset_atrasos', sa.Date(), nullable=True))
    op.create_index(op.f('ix_funcionarios_ultimo_reset_atrasos'), 'funcionarios', ['ultimo_reset_atrasos'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_funcionarios_ultimo_reset_atrasos'), table_name='funcionarios')
    op.drop_column('funcionarios', 'ultimo_reset_atrasos')
    # ### end Alembic commands ###
