"""add data_admissao e rh fase1

Revision ID: 2d2f5a0fe773
Revises: 0c546fe70766
Create Date: 2026-09-20 09:30:13.790689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2d2f5a0fe773'
down_revision: Union[str, Sequence[str], None] = '0c546fe70766'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_ponto',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('lat_sede', sa.Float(), nullable=True),
    sa.Column('lng_sede', sa.Float(), nullable=True),
    sa.Column('raio_permitido_m', sa.Integer(), nullable=False),
    sa.Column('hora_entrada', sa.String(length=5), nullable=False),
    sa.Column('tolerancia_min', sa.Integer(), nullable=False),
    sa.Column('exige_foto', sa.Boolean(), nullable=False),
    sa.Column('exige_localizacao', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('pedidos_rh',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('ferias', 'falta_justificada', 'doenca', 'licenca_maternidade', 'licenca_sem_vencimento', name='tipopedido'), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('dias_uteis', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('documento_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aprovado', 'rejeitado', 'cancelado', name='statuspedido'), nullable=False),
    sa.Column('aprovado_por_id', sa.UUID(), nullable=True),
    sa.Column('aprovado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observacao_gestor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedidos_rh_company_id'), 'pedidos_rh', ['company_id'], unique=False)
    op.create_index(op.f('ix_pedidos_rh_funcionario_id'), 'pedidos_rh', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_pedidos_rh_status'), 'pedidos_rh', ['status'], unique=False)
    op.create_table('pontos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('tipo', sa.Enum('entrada', 'pausa_inicio', 'pausa_fim', 'saida', name='tipoponto'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distancia_m', sa.Integer(), nullable=True),
    sa.Column('dentro_raio', sa.Boolean(), nullable=False),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('dispositivo', sa.String(length=100), nullable=True),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('justificado', sa.Boolean(), nullable=False),
    sa.Column('observacao_justificativa', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pontos_company_id'), 'pontos', ['company_id'], unique=False)
    op.create_index(op.f('ix_pontos_data'), 'pontos', ['data'], unique=False)
    op.create_index(op.f('ix_pontos_funcionario_id'), 'pontos', ['funcionario_id'], unique=False)
    op.create_table('recibos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('salario', 'bonus', 'decimo_terceiro', name='tiporecibo'), nullable=False),
    sa.Column('valor_bruto', sa.Float(), nullable=True),
    sa.Column('valor_descontos', sa.Float(), nullable=True),
    sa.Column('valor_liquido', sa.Float(), nullable=True),
    sa.Column('arquivo_pdf_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('rascunho', 'publicado', name='statusrecibo'), nullable=False),
    sa.Column('publicado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recibos_company_id'), 'recibos', ['company_id'], unique=False)
    op.create_index(op.f('ix_recibos_funcionario_id'), 'recibos', ['funcionario_id'], unique=False)
    op.create_table('saldo_ferias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('ano_referencia', sa.Integer(), nullable=False),
    sa.Column('dias_direito', sa.Integer(), nullable=False),
    sa.Column('dias_gozados', sa.Integer(), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saldo_ferias_company_id'), 'saldo_ferias', ['company_id'], unique=False)
    op.create_index(op.f('ix_saldo_ferias_funcionario_id'), 'saldo_ferias', ['funcionario_id'], unique=False)
    op.add_column('funcionarios', sa.Column('data_admissao', sa.Date(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('funcionarios', 'data_admissao')
    op.drop_index(op.f('ix_saldo_ferias_funcionario_id'), table_name='saldo_ferias')
    op.drop_index(op.f('ix_saldo_ferias_company_id'), table_name='saldo_ferias')
    op.drop_table('saldo_ferias')
    op.drop_index(op.f('ix_recibos_funcionario_id'), table_name='recibos')
    op.drop_index(op.f('ix_recibos_company_id'), table_name='recibos')
    op.drop_table('recibos')
    op.drop_index(op.f('ix_pontos_funcionario_id'), table_name='pontos')
    op.drop_index(op.f('ix_pontos_data'), table_name='pontos')
    op.drop_index(op.f('ix_pontos_company_id'), table_name='pontos')
    op.drop_table('pontos')
    op.drop_index(op.f('ix_pedidos_rh_status'), table_name='pedidos_rh')
    op.drop_index(op.f('ix_pedidos_rh_funcionario_id'), table_name='pedidos_rh')
    op.drop_index(op.f('ix_pedidos_rh_company_id'), table_name='pedidos_rh')
    op.drop_table('pedidos_rh')
    op.drop_table('config_ponto')
    # ### end Alembic commands ###
