"""add agt details columns

Revision ID: 3def3da8c39b
Revises: 8367c3295447
Create Date: 2026-09-18 17:07:29.460283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '3def3da8c39b'
down_revision: Union[str, Sequence[str], None] = '8367c3295447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('nif_verified', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('companies', sa.Column('nif_agt_name', sa.String(length=255), nullable=True))
    op.add_column('companies', sa.Column('nif_verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('tipo_agt', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('estado_agt', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('inadimplente', sa.String(length=10), nullable=True))
    op.add_column('companies', sa.Column('regime_iva', sa.String(length=150), nullable=True))
    op.add_column('companies', sa.Column('residente_fiscal', sa.String(length=20), nullable=True))
    op.add_column('companies', sa.Column('ultima_verificacao_agt', sa.DateTime(timezone=True), nullable=True))
    op.add_column('companies', sa.Column('bloqueado_pela_agt', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_companies_estado_agt'), 'companies', ['estado_agt'], unique=False)
    op.create_index(op.f('ix_subscriptions_comprovativo_hash'), 'subscriptions', ['comprovativo_hash'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    op.drop_index(op.f('ix_subscriptions_comprovativo_hash'), table_name='subscriptions')
    op.drop_index(op.f('ix_companies_estado_agt'), table_name='companies')
    op.drop_column('companies', 'bloqueado_pela_agt')
    op.drop_column('companies', 'ultima_verificacao_agt')
    op.drop_column('companies', 'residente_fiscal')
    op.drop_column('companies', 'regime_iva')
    op.drop_column('companies', 'inadimplente')
    op.drop_column('companies', 'estado_agt')
    op.drop_column('companies', 'tipo_agt')
    op.drop_column('companies', 'nif_verified_at')
    op.drop_column('companies', 'nif_agt_name')
    op.drop_column('companies', 'nif_verified')
