"""add justificativa falta

Revision ID: dbfcbaff7991
Revises: e59a4ca7ea63
Create Date: 2026-09-21 11:19:41.032315

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'dbfcbaff7991'
down_revision: Union[str, Sequence[str], None] = 'e59a4ca7ea63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos_rh', sa.Column('justificativa_tipo', sa.String(length=50), nullable=True))
    op.add_column('pedidos_rh', sa.Column('justificativa_obs', sa.Text(), nullable=True))
    op.add_column('pedidos_rh', sa.Column('justificativa_anexo_url', sa.Text(), nullable=True))
    op.add_column('pedidos_rh', sa.Column('justificado_em', sa.DateTime(timezone=True), nullable=True))
    op.add_column('pedidos_rh', sa.Column('justificado_por_id', sa.UUID(), nullable=True))
    op.add_column('pedidos_rh', sa.Column('abonada', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_pedidos_rh_justificado_por_id'), 'pedidos_rh', ['justificado_por_id'], unique=False)
    op.create_foreign_key('fk_pedidos_rh_justificado_por_id', 'pedidos_rh', 'funcionarios', ['justificado_por_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_pedidos_rh_justificado_por_id', 'pedidos_rh', type_='foreignkey')
    op.drop_index(op.f('ix_pedidos_rh_justificado_por_id'), table_name='pedidos_rh')
    op.drop_column('pedidos_rh', 'abonada')
    op.drop_column('pedidos_rh', 'justificado_por_id')
    op.drop_column('pedidos_rh', 'justificado_em')
    op.drop_column('pedidos_rh', 'justificativa_anexo_url')
    op.drop_column('pedidos_rh', 'justificativa_obs')
    op.drop_column('pedidos_rh', 'justificativa_tipo')
    # ### end Alembic commands ###
