"""add lancado_em retro

Revision ID: e59a4ca7ea63
Revises: fad26f7dc855
Create Date: 2026-09-20 16:24:44.992855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e59a4ca7ea63'
down_revision: Union[str, Sequence[str], None] = 'fad26f7dc855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedidos_rh', sa.Column('lancado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_pedidos_rh_is_retroativo'), 'pedidos_rh', ['is_retroativo'], unique=False)
    op.create_index(op.f('ix_pedidos_rh_lancado_por_id'), 'pedidos_rh', ['lancado_por_id'], unique=False)
    op.add_column('pontos', sa.Column('lancado_em', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_pontos_is_retroativo'), 'pontos', ['is_retroativo'], unique=False)
    op.create_index(op.f('ix_pontos_lancado_por_id'), 'pontos', ['lancado_por_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pontos_lancado_por_id'), table_name='pontos')
    op.drop_index(op.f('ix_pontos_is_retroativo'), table_name='pontos')
    op.drop_column('pontos', 'lancado_em')
    op.drop_index(op.f('ix_pedidos_rh_lancado_por_id'), table_name='pedidos_rh')
    op.drop_index(op.f('ix_pedidos_rh_is_retroativo'), table_name='pedidos_rh')
    op.drop_column('pedidos_rh', 'lancado_em')
    # ### end Alembic commands ###
