"""add iban2 to companies

Revision ID: ed3d8a0200e1
Revises: 3a1e90f13a63
Create Date: 2026-09-16 19:07:16.165835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed3d8a0200e1'
down_revision: Union[str, Sequence[str], None] = '3a1e90f13a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('iban', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('iban2', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('companies', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_index('ix_faturas_cliente_nome', table_name='faturas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_faturas_cliente_nome', 'faturas', ['cliente_nome'], unique=False)
    op.drop_column('companies', 'image_url')
    op.drop_column('companies', 'logo_url')
    op.drop_column('companies', 'iban2')
    op.drop_column('companies', 'iban')
    # ### end Alembic commands ###
