"""add modelos_documentos e documentos_gerados

Revision ID: ef28c89dfb25
Revises: 8f3c1d2a7b90
Create Date: 2026-09-24 23:00:29.461534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ef28c89dfb25'
down_revision: Union[str, Sequence[str], None] = '8f3c1d2a7b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modelos_documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.Enum('contrato_efetivo', 'contrato_estagio', 'contrato_temporario', 'contrato_experiencia', 'contrato_confidencialidade', 'aditivo_contratual', 'declaracao_trabalho', 'declaracao_vencimento', 'carta_recomendacao', 'carta_apresentacao', 'aviso_ferias', 'comunicacao_ferias', 'mapa_ferias', 'justificacao_falta', 'comunicacao_falta', 'horario_trabalho', 'advertencia_verbal', 'advertencia_escrita', 'processo_disciplinar', 'suspensao', 'aumento_salarial', 'alteracao_cargo', 'alteracao_salario', 'comunicacao_bonus', 'carta_demissao_funcionario', 'carta_demissao_empresa', 'declaracao_desvinculacao', 'certificado_trabalho', 'acordo_rescisao', 'outro', name='tipomodelodocumento'), nullable=False),
    sa.Column('categoria', sa.Enum('admissao', 'gestao', 'ferias_ponto', 'disciplinar', 'financeiro_carreira', 'saida', 'outros', name='categoriamodelo'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('conteudo_html', sa.Text(), nullable=False),
    sa.Column('conteudo_json', sa.JSON(), nullable=True),
    sa.Column('conteudo_texto', sa.Text(), nullable=True),
    sa.Column('variaveis_usadas', sa.JSON(), nullable=True),
    sa.Column('variaveis_obrigatorias', sa.JSON(), nullable=True),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('is_ativo', sa.Boolean(), nullable=False),
    sa.Column('is_padrao', sa.Boolean(), nullable=False),
    sa.Column('is_sistema', sa.Boolean(), nullable=False),
    sa.Column('header_config', sa.JSON(), nullable=True),
    sa.Column('footer_config', sa.JSON(), nullable=True),
    sa.Column('margens_config', sa.JSON(), nullable=True),
    sa.Column('fonte_config', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('criado_por_id', sa.UUID(), nullable=True),
    sa.Column('atualizado_por_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelos_documentos_categoria'), 'modelos_documentos', ['categoria'], unique=False)
    op.create_index(op.f('ix_modelos_documentos_codigo'), 'modelos_documentos', ['codigo'], unique=False)
    op.create_index(op.f('ix_modelos_documentos_company_id'), 'modelos_documentos', ['company_id'], unique=False)
    op.create_index(op.f('ix_modelos_documentos_is_ativo'), 'modelos_documentos', ['is_ativo'], unique=False)
    op.create_index(op.f('ix_modelos_documentos_is_padrao'), 'modelos_documentos', ['is_padrao'], unique=False)
    op.create_index(op.f('ix_modelos_documentos_tipo'), 'modelos_documentos', ['tipo'], unique=False)
    op.create_table('documentos_gerados',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('funcionario_id', sa.UUID(), nullable=False),
    sa.Column('modelo_id', sa.UUID(), nullable=True),
    sa.Column('modelo_versao', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('contrato_efetivo', 'contrato_estagio', 'contrato_temporario', 'contrato_experiencia', 'contrato_confidencialidade', 'aditivo_contratual', 'declaracao_trabalho', 'declaracao_vencimento', 'carta_recomendacao', 'carta_apresentacao', 'aviso_ferias', 'comunicacao_ferias', 'mapa_ferias', 'justificacao_falta', 'comunicacao_falta', 'horario_trabalho', 'advertencia_verbal', 'advertencia_escrita', 'processo_disciplinar', 'suspensao', 'aumento_salarial', 'alteracao_cargo', 'alteracao_salario', 'comunicacao_bonus', 'carta_demissao_funcionario', 'carta_demissao_empresa', 'declaracao_desvinculacao', 'certificado_trabalho', 'acordo_rescisao', 'outro', name='tipomodelodocumento'), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=300), nullable=False),
    sa.Column('codigo_verificacao', sa.String(length=50), nullable=False),
    sa.Column('conteudo_html_final', sa.Text(), nullable=False),
    sa.Column('dados_snapshot', sa.JSON(), nullable=False),
    sa.Column('variaveis_preenchidas', sa.JSON(), nullable=True),
    sa.Column('url_pdf', sa.Text(), nullable=True),
    sa.Column('url_docx', sa.Text(), nullable=True),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('gerado', 'assinado', 'cancelado', 'expirado', 'rascunho', name='statusdocumentogerado'), nullable=False),
    sa.Column('data_emissao', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_validade', sa.DateTime(timezone=True), nullable=True),
    sa.Column('data_assinatura', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assinado_por', sa.JSON(), nullable=True),
    sa.Column('gerado_por_id', sa.UUID(), nullable=True),
    sa.Column('motivo_cancelamento', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['modelo_id'], ['modelos_documentos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_gerados_codigo_verificacao'), 'documentos_gerados', ['codigo_verificacao'], unique=True)
    op.create_index(op.f('ix_documentos_gerados_company_id'), 'documentos_gerados', ['company_id'], unique=False)
    op.create_index(op.f('ix_documentos_gerados_funcionario_id'), 'documentos_gerados', ['funcionario_id'], unique=False)
    op.create_index(op.f('ix_documentos_gerados_gerado_por_id'), 'documentos_gerados', ['gerado_por_id'], unique=False)
    op.create_index(op.f('ix_documentos_gerados_modelo_id'), 'documentos_gerados', ['modelo_id'], unique=False)
    op.create_index(op.f('ix_documentos_gerados_status'), 'documentos_gerados', ['status'], unique=False)
    op.create_index(op.f('ix_documentos_gerados_tipo'), 'documentos_gerados', ['tipo'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documentos_gerados_tipo'), table_name='documentos_gerados')
    op.drop_index(op.f('ix_documentos_gerados_status'), table_name='documentos_gerados')
    op.drop_index(op.f('ix_documentos_gerados_modelo_id'), table_name='documentos_gerados')
    op.drop_index(op.f('ix_documentos_gerados_gerado_por_id'), table_name='documentos_gerados')
    op.drop_index(op.f('ix_documentos_gerados_funcionario_id'), table_name='documentos_gerados')
    op.drop_index(op.f('ix_documentos_gerados_company_id'), table_name='documentos_gerados')
    op.drop_index(op.f('ix_documentos_gerados_codigo_verificacao'), table_name='documentos_gerados')
    op.drop_table('documentos_gerados')
    op.drop_index(op.f('ix_modelos_documentos_tipo'), table_name='modelos_documentos')
    op.drop_index(op.f('ix_modelos_documentos_is_padrao'), table_name='modelos_documentos')
    op.drop_index(op.f('ix_modelos_documentos_is_ativo'), table_name='modelos_documentos')
    op.drop_index(op.f('ix_modelos_documentos_company_id'), table_name='modelos_documentos')
    op.drop_index(op.f('ix_modelos_documentos_codigo'), table_name='modelos_documentos')
    op.drop_index(op.f('ix_modelos_documentos_categoria'), table_name='modelos_documentos')
    op.drop_table('modelos_documentos')
    # ### end Alembic commands ###
