"""empty message

Revision ID: fc1ed3cb2c9a
Revises: 2d2f5a0fe773
Create Date: 2026-09-20 12:05:23.837336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1ed3cb2c9a'
down_revision: Union[str, Sequence[str], None] = '2d2f5a0fe773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_ponto', sa.Column('regra_atraso_ativa', sa.Boolean(), nullable=False))
    op.add_column('config_ponto', sa.Column('qtd_atrasos_para_falta', sa.Integer(), nullable=False))
    op.add_column('config_ponto', sa.Column('periodo_regra', sa.String(length=10), nullable=False))
    op.add_column('pontos', sa.Column('atraso_min', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pontos', 'atraso_min')
    op.drop_column('config_ponto', 'periodo_regra')
    op.drop_column('config_ponto', 'qtd_atrasos_para_falta')
    op.drop_column('config_ponto', 'regra_atraso_ativa')
    # ### end Alembic commands ###
